SocialDistribution/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('app.urls')),
    path('api/', include('api.urls')),
]

api/urls.py
from django.contrib.auth.decorators import login_required
from django.urls import path, include
from rest_framework import routers

import api.views as views
import api.views.author_views
import api.views.comment_views
import api.views.friend_views
import api.views.post_views

app_name = 'api'

from rest_framework_swagger.views import get_swagger_view

# Taken from https://django-rest-swagger.readthedocs.io/en/latest/
schema_view = get_swagger_view(title='Group 10 Social Distribution Remote API')

urlpatterns = [
    path('', schema_view),
    # Author
    path('author/<uuid:id>', api.views.author_views.AuthorView.as_view(), name='author'),
    path('author/', api.views.author_views.AuthorListView.as_view(), name='author_list'),

    # Posts
    path('posts', api.views.post_views.PublicPostView.as_view(), name='public'),
    path('author/posts', api.views.post_views.AuthorVisiblePostView.as_view(), name='author_visible'),
    path('author-mutual/posts', api.views.post_views.AuthorMutualPostView.as_view(), name='author_mutual_visible'),
    path('author/<uuid:id>/posts', api.views.post_views.AuthorPostView.as_view(), name='author_posts'),
    path('posts/<uuid:id>', api.views.post_views.SinglePostView.as_view(), name='single_post'),

    # Comments
    path('posts/<uuid:id>/comments', api.views.comment_views.CommentsView.as_view(), name='comments'),

    # Friends
    #path('author/<uuid:id>/friends', api.views.friend_views.FriendView.as_view(), name='friends'),
    path('author/<uuid:id>/friends/', api.views.friend_views.FriendResponseView.as_view(), name='friends'),
    path('author/<uuid:id>/friends/<uuid:id2>', api.views.friend_views.IsFriendView.as_view(), name='is_friend'),
    path('author/friends', api.views.friend_views.FriendView2.as_view(), name='friends2'),
    path('author/<uuid:id>/following', api.views.friend_views.FollowingView.as_view(), name='following'),
    path('author/following', api.views.friend_views.FollowingView2.as_view(), name='following2'),
    path('author/<uuid:id>/followers', api.views.friend_views.FollowerView.as_view(), name='followers'),
    path('author/followers', api.views.friend_views.FollowerView2.as_view(), name='followers2'),

    # Friendrequest
    path('friendrequest', api.views.friend_views.FriendRequestView.as_view(), name='friendrequest'),

]

app/urls.py
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static

import app.views.post_views
import app.views.user_views
from app.views import views, post_views, user_views

app_name = 'app'

urlpatterns = [
    path('api_test', views.api_test, name='api_test'),
    # path('api/', include(router.urls)),
    path('', views.index),
    path('index', views.index, name="index"),
    path('accounts/login/', views.login_view, name='login'),
    path('accounts/logout', views.logout_view, name="logout"),
    path('register', views.register_view, name="register"),
    path('create-image', app.views.post_views.create_image_view, name="create_image"),
    path('images/<str:filename>', views.get_image, name="images"),
    path('images/<str:filename>/<str:encoding>', views.get_image, name="images"),
    path('my-posts', app.views.post_views.my_posts_view, name="my_posts"),
    path('create-post', app.views.post_views.create_post_view, name='create_post'),
    path('delete/<uuid:id>/', app.views.post_views.delete_post, name="delete"),
    path('author/<uuid:id>', views.profile_view, name="profile"),
    path('profile', views.my_profile_view, name="my_profile"),
    path('profile/edit/', views.edit_profile, name="edit_profile"),
    path('post/edit/<uuid:id>/', post_views.edit_post, name="edit_post"),
    path('authors', user_views.all_author_view, name="all_authors"),
    path('authors/follow/<uuid:id>/', user_views.follow_view, name="follow"),
    # path('followers/follow/<uuid:id>/', user_views.follow_view, name="followers_follow"),
    path('authors/unfollow/<uuid:id>/', user_views.unfollow_view, name="unfollow"),
    path('authors/unfollow-mutual/<uuid:id>/', user_views.unfollow_mutual_view, name="unfollow_mutual"),
    path('public-posts', app.views.post_views.public_post_view, name="public_posts"),
    path('private-posts', app.views.post_views.private_friends_posts_view, name="private_posts"),
    path('search/', views.search_view, name="search_author"),
    path('new_followers/', user_views.new_followers_view, name="new_followers"),
    path('followers/', user_views.all_followers_view, name="followers"),

    path('mutual-friends/', user_views.mutual_friends_view, name="mutual_friends"),
    path('post-detail/<uuid:id>/', post_views.create_comment_view, name="post_detail"),
    path('foaf-posts', post_views.foaf_posts_view, name="foaf_posts"),
    path('mutual-friend-posts', post_views.mutual_friends_posts_view, name="mutual_friend_posts"),
    path('post/<uuid:id>/', post_views.unlisted_post_view, name="unlisted_post"),

    path('author/remote/', app.views.user_views.profile_remote_view, name="author_remote"),
    path('post-detail/remote/<str:post>', post_views.remote_post_view, name="remote_post"),

    path('friend-request/send/<uuid:id>',user_views.send_friend_request, name='add_friend'),
    path('friend-request/cancel/<uuid:id>',user_views.cancel_friend_request, name='cancel_friend'),
    path('friend-request/accept/<uuid:id>',user_views.accept_friend_request, name='accept_friend'),
    path('friendrequest', user_views.all_requests_view, name="requests"),

    path('remote-friend-request/accept/',user_views.accept_remote_friend_request, name='accept_remote_friend'),
    path('remote-friend-request/cancel/',user_views.cancel_remote_friend_request, name='cancel_remote_friend'),
    path('remote-friend-request/send/<str:uuid>',user_views.send_remote_friend_request, name='add_remote_friend'),
    path('unfollow-remote-mutual/<str:uuid>', user_views.unfriend_remote_mutual_view, name="unfriend_remote_mutual"),

    #path('friendrequest', api_views.friendrequest, name="friendrequest"),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

app/models.py
import uuid

from django.db import models
from django.contrib.auth.models import User
from django.db.models.signals import post_save
from django.dispatch import receiver

from settings_server import *
from django.forms import ModelForm
from django.utils.html import mark_safe
from markdown import markdown


def image_content_to_html(content):
    return mark_safe("<img src=\"" + content + "\" />")


class Author(models.Model):
    """
    user: a local user using the Django User
    username: username from either a local user or remote
    host_url: host url
    github_url: optional github url from an author
    """
    user = models.OneToOneField(User, related_name='user', on_delete=models.CASCADE, blank=True, null=True)
    username = models.CharField(max_length=50, unique=True, blank=True, null=True)
    bio = models.TextField(blank=True, null=True)
    host_url = models.URLField(blank=True, null=True)  # Url of different hosts
    github_url = models.CharField(max_length=100, blank=True, null=True)  # Optional
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False, blank=False)
    url = models.CharField(max_length=150, blank=True, null=True)
    friends = models.ManyToManyField("self", blank=True, related_name='author_friends')
    image = models.ImageField(upload_to='profile_pics', blank=True)

    @property
    def full_name(self):
        if self.user:
            return self.user.get_full_name()

    def __str__(self):
        return "{} - {}".format(str(self.username), self.host_url)

    def save(self, *args, **kwargs):
        if not self.id:
            self.id = uuid.uuid4()
        self.url = "{}/author/{}".format(self.host_url, self.id)
        super(self.__class__, self).save(*args, **kwargs)


class FollowRequest(models.Model):
    author = models.ForeignKey(Author, related_name='author_request', on_delete=models.CASCADE)
    friend = models.ForeignKey(Author, related_name='friend_request', on_delete=models.CASCADE)
    acknowledged = models.BooleanField(default=False)
    date_created = models.DateTimeField(auto_now=True)

    def __str__(self):
        return "{} {} - {}".format(self.author.username, self.friend.username, self.acknowledged)

    def get_following(self):
        return self.friend.username


class FriendRequest(models.Model):
    author = models.ForeignKey(Author, related_name='to_user', on_delete=models.CASCADE)
    friend = models.ForeignKey(Author, related_name='from_user', on_delete=models.CASCADE)
    # acknowledged = models.BooleanField(default=False)
    timestamp = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return "From {}, to {}".format(self.author.username, self.friend.username)


POST_PRIVACY = (
    ('PRIVATE', 'Private'),
    ('SERVERONLY', 'All friends on my host'),
    ('FRIENDS', 'All friends'),
    ('FOAF', 'My friends friends'),
    ('PUBLIC', 'Public'),
)

POST_CONTENT_TYPE = (
    ('text/plain', 'Plain Text'),
    ('text/markdown', 'Markdown'),
    ('image/png;base64', 'PNG Base64'),
    ('image/jpeg;base64', 'JPEG Base64')
)


class Post(models.Model):
    # TODO: Finish this class
    author = models.ForeignKey(Author, related_name='authorPost', on_delete=models.CASCADE)
    published = models.DateTimeField(auto_now=True)
    title = models.CharField(max_length=100, blank=True, null=True)
    description = models.CharField(max_length=50, blank=True, null=True)  # brief description
    visibility = models.CharField(max_length=100, choices=POST_PRIVACY, default='Private')
    visibleTo = models.ManyToManyField(Author, blank=True, related_name='visibleTo')
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False, blank=False)
    content = models.TextField(default="")
    contentType = models.CharField(max_length=100, choices=POST_CONTENT_TYPE, default='Plain Text')
    unlisted = models.BooleanField(default=False)

    def __str__(self):
        return "{} - {} - {}".format(self.author, self.published, self.visibility)

    def __repr__(self):
        return "{} - {} - {}".format(self.author, self.published, self.visibility)

    def get_content(self):
        if self.contentType == "text/markdown":
            return mark_safe(markdown(self.content, safe_mode='escape'))
        elif self.contentType.startswith("image/"):
            return image_content_to_html(self.content)
        else:
            return self.content


class Comment(models.Model):
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False, blank=False)
    post = models.ForeignKey(Post, related_name='CommentPost', on_delete=models.CASCADE)
    author = models.ForeignKey(Author, related_name='authorComment', on_delete=models.CASCADE)
    comment = models.TextField(default="")
    contentType = models.CharField(max_length=100, choices=POST_CONTENT_TYPE, default='Plain Text')
    published = models.DateTimeField(auto_now=True)

    def __str__(self):
        return "{} - {} - {}".format(self.author, self.published, self.id)

    def __repr__(self):
        return "{} - {} - {} ".format(self.author, self.published, self.id)

    def get_comment(self):
        if self.contentType == "text/markdown":
            return mark_safe(markdown(self.comment, safe_mode='escape'))
        else:
            return self.comment


class Server(models.Model):
    # TODO: Finish this class
    hostname = models.CharField(max_length=50, unique=True, blank=True, null=True)
    user = models.OneToOneField(User, related_name='server_user', on_delete=models.CASCADE, blank=True, null=True)
    username = models.CharField(max_length=50, unique=True, blank=True, null=True)
    password = models.CharField(max_length=50, unique=True, blank=True, null=True)
    no_posts = models.BooleanField(default=False)
    no_images = models.BooleanField(default=False)

    def __str__(self):
        return "Hostname: {}".format(self.hostname)


class RemoteComment(models.Model):
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False, blank=False)
    post = models.ForeignKey(Post, related_name='RemoteCommentPost', on_delete=models.CASCADE)
    server = models.ForeignKey(Server, related_name="RemoteServer", on_delete=models.CASCADE)
    author = models.URLField(blank=True, null=True)
    comment = models.TextField(default="")
    contentType = models.CharField(max_length=100, choices=POST_CONTENT_TYPE, default='Plain Text')
    published = models.DateTimeField()

    def __str__(self):
        return "{} - {}".format(self.post.title, self.published)

    def __repr__(self):
        return "{} - {}".format(self.post.title, self.published)

    def get_comment(self):
        if self.contentType == "text/markdown":
            return mark_safe(markdown(self.comment, safe_mode='escape'))
        else:
            return self.comment


@receiver(post_save, sender=User)
def create_user_author(sender, instance, created, **kwargs):
    if created:
        Author.objects.create(user=instance, host_url=DOMAIN)
        instance.user.author_id = uuid.uuid4()
        instance.user.url = "{}/api/author/{}".format(instance.user.host_url, instance.user.author_id)
        instance.user.username = instance.username
        instance.user.save()


class RemoteFriendRequest(models.Model):
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False, blank=False)
    author = models.URLField(blank=True, null=True)  # id
    host = models.URLField(blank=True, null=True)  # host
    displayName = models.CharField(max_length=50, unique=True, blank=True, null=True)  # display name
    url = models.URLField(blank=True, null=True)
    friend = models.ForeignKey(Author, related_name='RemoteFriend', on_delete=models.CASCADE)  # Always a local author
    timestamp = models.DateTimeField(auto_now_add=True)
    server = models.ForeignKey(Server, related_name="RemoteFriendServer", on_delete=models.CASCADE)

    def __str__(self):
        return "From {}, to {}".format(self.author, self.friend.username)


class RemoteFriend(models.Model):
    author = models.ForeignKey(Author, related_name="author_re", on_delete=models.CASCADE, null=True)
    host = models.URLField(blank=True, null=True)  # host
    displayName = models.CharField(max_length=50, unique=True, blank=True, null=True)  # display name
    url = models.URLField(blank=True, null=True)
    friend = models.URLField(blank=True, null=True)
    server = models.ForeignKey(Server, related_name='remote_server', on_delete=models.CASCADE, null=True)


class PendingRemoteFriend(models.Model):
    author = models.ForeignKey(Author, related_name="sender", on_delete=models.CASCADE, null=True)
    host = models.URLField(blank=True, null=True)  # host
    displayName = models.CharField(max_length=50, unique=True, blank=True, null=True)  # display name
    url = models.URLField(blank=True, null=True)
    friend = models.URLField(blank=True, null=True)
    server = models.ForeignKey(Server, related_name='pending_remote_server', on_delete=models.CASCADE, null=True)

app/forms/post_forms.py
from django.forms import ModelForm, inlineformset_factory
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserChangeForm

from app.models import Post, Author, Comment

class AuthorForm(ModelForm):
    author_id = forms.CharField()
    host = forms.CharField(label="hello")
    displayName = forms.CharField()
    url = forms.CharField()

    class Meta:
        model = Author
        fields = (
            'author_id',
            'host',
            'displayName',
            'url',
            )

class PostCreateForm(ModelForm):
    content = forms.Textarea()
    title = forms.CharField()
    description = forms.CharField()

    class Meta:
        model = Post
        exclude = ('author', 'published')


class EditProfileForm(ModelForm):
    class Meta:
        model = User
        fields = (
            'first_name',
            'last_name',
        )


class EditBio(ModelForm):
    username = forms.CharField()

    class Meta:
        model = Author
        fields = (
            'username',
            'bio',
            'github_url',
        )


class CommentCreateForm(ModelForm):
    comment = forms.Textarea()

    class Meta:
        model = Comment
        exclude = (
            'post',
            'author',
            'published'
        )

app/templates/authors/all_authors.html
{% extends 'base.html' %}

DEFAULT_IMAGE = "https://www.betwext.com/wp-content/uploads/2018/09/blank-profile-picture-973460_640.png"
{% block page_title %}
    401 Group | All Authors
{% endblock %}

{% block content %}
    <h1 class="h3 mb-4 text-gray-800">All Authors</h1>
    <div>
        {% for author in authors %}

            <div class="card shadow mb-4">
                <!-- Card Header - Accordion -->
                <div class="d-block card-header py-3">
                    <div class="inline-group">
                        {% if author.image %}
                            <img class="img-circle" style="border-radius: 50%; object-fit: cover;" width="50"
                                 height="50"
                                 src="{{ author.image.url }}">
                        {% else %}
                            <img class="img-circle" style="border-radius: 50%; object-fit: cover;" width="50"
                                 height="50"
                                 src="https://www.betwext.com/wp-content/uploads/2018/09/blank-profile-picture-973460_640.png"/>
                        {% endif %}


                        <a href="/author/{{ author.id }}" class="ml-2 font-weight-bold text-primary">
                            {{ author.username }}
                        </a>
                        <div style="margin-left: 4em;">
                            <h6 style="text-transform: uppercase">{{ author.user.first_name }} {{ author.user.last_name }}</h6>
                            <h6>Host: {{ author.host_url }}</h6>
                        </div>
                    </div>
                </div>

                <!-- Card Content - Collapse -->
                <div class="card-footer">
                        <span>
                            {% if author in friends %}
                                <a href="{% url 'app:unfollow_mutual' id=author.id %}" class="btn btn-danger">Unfriend</a>
                            {% elif author in pending %}
                                <a href="" class="btn btn-warning">Pending</a>
                            {% else %}
                                <a href="{% url 'app:add_friend' id=author.id %}" class="btn btn-primary">Add Friend</a>
                            {% endif %}

                        </span>
                </div>
            </div>

        {% endfor %}
    </div>
{% endblock %}

app/templates/authors/follower_request.html
{% extends 'base.html' %}


{% block page_title %}
    401 Group | New Followers
{% endblock %}

{% block content %}
    <h1 class="h3 mb-4 text-gray-800">New Friend Follows</h1>
    <div>
        {% for follower in followers_new %}
            <div class="card shadow mb-4">
                <!-- Card Header - Accordion -->
                <div class="d-block card-header py-3">
                    <h6 class="m-0 font-weight-bold text-primary">{{ follower.author.username }}
                        - {{ follower.date_created }}
                    </h6>
{#                    <a href="/author/{{ follower.author.id }}" role="button" aria-expanded="true">#}
{#                        <h6 class="m-0 font-weight-bold text-primary">{{ follower.author.username }}</h6>#}
{#                    </a>#}
{#                    <h6 class="m-0 font-weight-bold text-primary">Created: {{ follower.date_created }}#}
{#                    </h6>#}
                </div>
            </div>
        {% endfor %}
    </div>
{% endblock %}

app/templates/authors/followers.html
{% extends 'base.html' %}


{% block page_title %}
    401 Group | All Followers
{% endblock %}

{% block content %}
    <h1 class="h3 mb-4 text-gray-800">Followers</h1>
    <div>
        {% if followers %}
            {% for follower in followers %}
                <div class="card shadow mb-4">
                    <!-- Card Header - Accordion -->
                    <div class="d-block card-header py-3">
                        <div class="inline-group">
                            {% if follower.author.image %}
                                <img class="img-circle" style="border-radius: 50%; object-fit: cover;" width="50"
                                     height="50"
                                     src="{{ follower.author.image.url }}">
                            {% else %}
                                <img class="img-circle" style="border-radius: 50%; object-fit: cover;" width="50"
                                     height="50"
                                     src="https://www.betwext.com/wp-content/uploads/2018/09/blank-profile-picture-973460_640.png"/>
                            {% endif %}

                            <a href="/author/{{ follower.author.id }}" class="ml-2 font-weight-bold text-primary">
                                {{ follower.author.username }}
                            </a>
                            <div style="margin-left: 4em;">
                                <h6 style="text-transform: uppercase">{{ follower.author.user.first_name }} {{ follower.author.user.last_name }}</h6>
                                <h6>URL {{ follower.author.host_url }}</h6>
                            </div>
                        </div>
                    </div>

                    {% if follower.author not in followings %}
                        <!-- Card Content - Collapse -->
                        <div class="card-footer">
                            <span>
                                <a href="{% url 'app:followers_follow' id=follower.author.id %}"
                                       class="btn btn-warning">Follow</a>
                            </span>
                        </div>
                    {% endif %}
                </div>
            {% endfor %}
        {% else %}
            You currently have no followers.
        {% endif %}
    </div>
{% endblock %}

app/templates/authors/following.html
{% extends 'base.html' %}


{% block page_title %}
    404 Group | Friend Requests
{% endblock %}

{% block content %}
    <h1 class="h3 mb-4 text-gray-800">Friend Requests</h1>
    <div>
        {% if requests %}
            {% for follower in requests %}
                <div class="card shadow mb-4">
                    <!-- Card Header - Accordion -->
                    <div class="d-block card-header py-3">
                        <div class="inline-group">
                            {% if follower.author.image %}
                                <img class="img-circle" style="border-radius: 50%; object-fit: cover;" width="50"
                                     height="50"
                                     src="{{ follower.author.image.url }}">
                            {% else %}
                                <img class="img-circle" style="border-radius: 50%; object-fit: cover;" width="50"
                                     height="50"
                                     src="https://www.betwext.com/wp-content/uploads/2018/09/blank-profile-picture-973460_640.png"/>
                            {% endif %}

                            <a href="/author/{{ follower.author.id }}" class="ml-2 font-weight-bold text-primary">
                                {{ follower.author.username }}
                            </a>
                            <div style="margin-left: 4em;">
                                {% if follower.remote %}
                                    <h6 style="text-transform: uppercase">{{ follower.author.first_name }} {{ follower.author.last_name }}</h6>
                                {% else %}
                                    <h6 style="text-transform: uppercase">{{ follower.author.user.first_name }} {{ follower.author.user.last_name }}</h6>
                                {% endif %}
                                <h6>URL {{ follower.author.host_url }}</h6>
                            </div>
                        </div>
                    </div>
                    <div class="card-footer">
                        {% if follower.remote %}
                            <a href="{% url 'app:accept_remote_friend' %}?id={{ follower.author_id }}"
                               class="btn btn-success">Accept Friend</a>
                            <a href="{% url 'app:cancel_remote_friend' %}?id={{ follower.author_id }}"
                               class="btn btn-danger">Cancel Friend</a>
                        {% else %}
                            <span>
                            <a href="{% url 'app:accept_friend' id=follower.author.id %}"
                               class="btn btn-success">Accept Friend</a>
                            <a href="{% url 'app:cancel_friend' id=follower.author.id %}"
                               class="btn btn-danger">Cancel Friend</a>
                        </span>
                        {% endif %}

                    </div>
                </div>
            {% endfor %}
        {% else %}
            <h5>You currently have no friend request.</h5>
        {% endif %}
    </div>
{% endblock %}

app/templates/authors/friendrequest.html
{% extends 'base.html' %}


{% block page_title %}
    401 Group 10 | Create Post
{% endblock %}

{% block content %}
    <h1 class="h3 mb-4 text-gray-800">Friend Request</h1>
    <div>
        <form action="" method="POST">
            {% csrf_token %}
            <div class="col-lg-8">
                <!-- /.panel-heading -->
                <div class="form-group row">
                    <label for="id_title" class="col-form-label">Author Id<span class="text-danger">*</span></label>
                    {{ form.post.errors }}
                    <input type="text" id="id_author_id" name="author_id" class="form-control"
                           placeholder="Author id"
                           value="{{ form.title.value|default:"" }}" autofocus required>

                </div>
                <div class="form-group row">
                    <label for="id_host_name" class="col-form-label">Hostname<span
                            class="text-danger">*</span></label>

                    <input type="text" id="id_host_name" name="host" class="form-control"
                           placeholder="Host name"
                           value="{{ form.description.value|default:"" }}" autofocus required>

                </div>
                
                <div class="form-group row">
                    <label for="id_display_name" class="col-form-label">Display name<span
                            class="text-danger">*</span></label>

                    <input type="text" id="id_display_name" name="displayName" class="form-control"
                           placeholder="Display name"
                           value="{{ form.description.value|default:"" }}" autofocus required>

                </div>

                <div class="form-group row">
                    <label for="id_url" class="col-form-label">URL<span
                            class="text-danger">*</span></label>

                    <input type="text" id="id_url" name="url" class="form-control"
                           placeholder="url"
                           value="{{ form.description.value|default:"" }}" autofocus required>

                </div>

            </div>
            {% if messages %}
                <ul class="messages">
                    {% for message in messages %}
                        <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
                    {% endfor %}
                </ul>
            {% endif %}
            <button class="btn btn-primary" type="submit">Submit</button>
        </form>
    </div>
{% endblock %}

app/templates/authors/mutual_friends.html
{% extends 'base.html' %}
{% load tz %}


{% block page_title %}
    401 Group | All Following
{% endblock %}

{% block content %}
    <h1 class="h3 mb-4 text-gray-800">Mutual Friends</h1>
    <div>
        {% if friends %}
            {% for friend in friends %}
                <div class="card shadow mb-4">
                    <!-- Card Header - Accordion -->
                    <a href="#collapseCardExample{{ friend.id }}" class="d-block card-header py-3"
                       data-toggle="collapse"
                       role="button"
                       aria-expanded="true" aria-controls="collapseCardExample">
                        <h6 class="m-0 font-weight-bold text-primary">{{ friend.username }}
                            - {{ friend.host_url }}
                        </h6>

                    </a>
                    <div class="collapse show" id="collapseCardExample{{ friend.id }}">
                        <div class="card-body">
                            {% for post in posts %}
                                {% if post.author == friend %}
                                    <div class="card shadow mb-4">
                                        <!-- Card Header - Accordion -->
                                        <div class="d-block card-header py-3">
                                            <h6 class="m-0 font-weight-bold text-primary">{{ post.title }}
                                                - {{ post.published }}
                                            </h6>
                                        </div>
                                        <div class="card-body">
                                            {{ post.get_content }}
                                        </div>
                                        <div class="card-footer">

                        <span>
                            <a href="{% url "app:post_detail" id=post.id %}" class="btn btn-outline-primary">View Comments / Comment</a>
                        </span>
                                        </div>

                                    </div>
                                {% endif %}
                            {% endfor %}

                        </div>
                    </div>
                    <div class="card-footer">
                        <span>
                            {% if friend.remote %}
                                <a href="{% url 'app:unfriend_remote_mutual' uuid=friend.uuid %}?host={{ friend.host_url }}"
                                   class="btn btn-danger">Unfriend</a>
                            {% else %}
                                <a href="{% url 'app:unfollow_mutual' id=friend.id %}"
                                   class="btn btn-danger">Unfriend</a>
                            {% endif %}

                        </span>
                    </div>
                </div>
            {% endfor %}
        {% else %}
            <h5>You currently have no mutual friends.</h5>
        {% endif %}
    </div>
{% endblock %}