SocialDistribution/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('app.urls')),
    path('api/', include('api.urls')),
]

api/urls.py
from django.contrib.auth.decorators import login_required
from django.urls import path, include
from rest_framework import routers

import api.views as views
import api.views.author_views
import api.views.comment_views
import api.views.friend_views
import api.views.post_views

app_name = 'api'

from rest_framework_swagger.views import get_swagger_view

# Taken from https://django-rest-swagger.readthedocs.io/en/latest/
schema_view = get_swagger_view(title='Group 10 Social Distribution Remote API')

urlpatterns = [
    path('', schema_view),
    # Author
    path('author/<uuid:id>', api.views.author_views.AuthorView.as_view(), name='author'),
    path('author/', api.views.author_views.AuthorListView.as_view(), name='author_list'),

    # Posts
    path('posts', api.views.post_views.PublicPostView.as_view(), name='public'),
    path('author/posts', api.views.post_views.AuthorVisiblePostView.as_view(), name='author_visible'),
    path('author-mutual/posts', api.views.post_views.AuthorMutualPostView.as_view(), name='author_mutual_visible'),
    path('author/<uuid:id>/posts', api.views.post_views.AuthorPostView.as_view(), name='author_posts'),
    path('posts/<uuid:id>', api.views.post_views.SinglePostView.as_view(), name='single_post'),

    # Comments
    path('posts/<uuid:id>/comments', api.views.comment_views.CommentsView.as_view(), name='comments'),

    # Friends
    #path('author/<uuid:id>/friends', api.views.friend_views.FriendView.as_view(), name='friends'),
    path('author/<uuid:id>/friends/', api.views.friend_views.FriendResponseView.as_view(), name='friends'),
    path('author/<uuid:id>/friends/<uuid:id2>', api.views.friend_views.IsFriendView.as_view(), name='is_friend'),
    path('author/friends', api.views.friend_views.FriendView2.as_view(), name='friends2'),
    path('author/<uuid:id>/following', api.views.friend_views.FollowingView.as_view(), name='following'),
    path('author/following', api.views.friend_views.FollowingView2.as_view(), name='following2'),
    path('author/<uuid:id>/followers', api.views.friend_views.FollowerView.as_view(), name='followers'),
    path('author/followers', api.views.friend_views.FollowerView2.as_view(), name='followers2'),

    # Friendrequest
    path('friendrequest', api.views.friend_views.FriendRequestView.as_view(), name='friendrequest'),

]

app/urls.py
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static

import app.views.post_views
import app.views.user_views
from app.views import views, post_views, user_views

app_name = 'app'

urlpatterns = [
    path('api_test', views.api_test, name='api_test'),
    # path('api/', include(router.urls)),
    path('', views.index),
    path('index', views.index, name="index"),
    path('accounts/login/', views.login_view, name='login'),
    path('accounts/logout', views.logout_view, name="logout"),
    path('register', views.register_view, name="register"),
    path('create-image', app.views.post_views.create_image_view, name="create_image"),
    path('images/<str:filename>', views.get_image, name="images"),
    path('images/<str:filename>/<str:encoding>', views.get_image, name="images"),
    path('my-posts', app.views.post_views.my_posts_view, name="my_posts"),
    path('create-post', app.views.post_views.create_post_view, name='create_post'),
    path('delete/<uuid:id>/', app.views.post_views.delete_post, name="delete"),
    path('author/<uuid:id>', views.profile_view, name="profile"),
    path('profile', views.my_profile_view, name="my_profile"),
    path('profile/edit/', views.edit_profile, name="edit_profile"),
    path('post/edit/<uuid:id>/', post_views.edit_post, name="edit_post"),
    path('authors', user_views.all_author_view, name="all_authors"),
    path('authors/follow/<uuid:id>/', user_views.follow_view, name="follow"),
    # path('followers/follow/<uuid:id>/', user_views.follow_view, name="followers_follow"),
    path('authors/unfollow/<uuid:id>/', user_views.unfollow_view, name="unfollow"),
    path('authors/unfollow-mutual/<uuid:id>/', user_views.unfollow_mutual_view, name="unfollow_mutual"),
    path('public-posts', app.views.post_views.public_post_view, name="public_posts"),
    path('private-posts', app.views.post_views.private_friends_posts_view, name="private_posts"),
    path('search/', views.search_view, name="search_author"),
    path('new_followers/', user_views.new_followers_view, name="new_followers"),
    path('followers/', user_views.all_followers_view, name="followers"),

    path('mutual-friends/', user_views.mutual_friends_view, name="mutual_friends"),
    path('post-detail/<uuid:id>/', post_views.create_comment_view, name="post_detail"),
    path('foaf-posts', post_views.foaf_posts_view, name="foaf_posts"),
    path('mutual-friend-posts', post_views.mutual_friends_posts_view, name="mutual_friend_posts"),
    path('post/<uuid:id>/', post_views.unlisted_post_view, name="unlisted_post"),

    path('author/remote/', app.views.user_views.profile_remote_view, name="author_remote"),
    path('post-detail/remote/<str:post>', post_views.remote_post_view, name="remote_post"),

    path('friend-request/send/<uuid:id>',user_views.send_friend_request, name='add_friend'),
    path('friend-request/cancel/<uuid:id>',user_views.cancel_friend_request, name='cancel_friend'),
    path('friend-request/accept/<uuid:id>',user_views.accept_friend_request, name='accept_friend'),
    path('friendrequest', user_views.all_requests_view, name="requests"),

    path('remote-friend-request/accept/',user_views.accept_remote_friend_request, name='accept_remote_friend'),
    path('remote-friend-request/cancel/',user_views.cancel_remote_friend_request, name='cancel_remote_friend'),
    path('remote-friend-request/send/<str:uuid>',user_views.send_remote_friend_request, name='add_remote_friend'),
    path('unfollow-remote-mutual/<str:uuid>', user_views.unfriend_remote_mutual_view, name="unfriend_remote_mutual"),

    #path('friendrequest', api_views.friendrequest, name="friendrequest"),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

app/forms/post_forms.py
from django.forms import ModelForm, inlineformset_factory
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserChangeForm

from app.models import Post, Author, Comment

class AuthorForm(ModelForm):
    author_id = forms.CharField()
    host = forms.CharField(label="hello")
    displayName = forms.CharField()
    url = forms.CharField()

    class Meta:
        model = Author
        fields = (
            'author_id',
            'host',
            'displayName',
            'url',
            )

class PostCreateForm(ModelForm):
    content = forms.Textarea()
    title = forms.CharField()
    description = forms.CharField()

    class Meta:
        model = Post
        exclude = ('author', 'published')


class EditProfileForm(ModelForm):
    class Meta:
        model = User
        fields = (
            'first_name',
            'last_name',
        )


class EditBio(ModelForm):
    username = forms.CharField()

    class Meta:
        model = Author
        fields = (
            'username',
            'bio',
            'github_url',
        )


class CommentCreateForm(ModelForm):
    comment = forms.Textarea()

    class Meta:
        model = Comment
        exclude = (
            'post',
            'author',
            'published'
        )

api/views/post_views.py
import requests
from django.http import HttpResponse
from rest_framework.generics import get_object_or_404
from rest_framework.permissions import IsAuthenticated
from rest_framework.response import Response
from rest_framework.views import APIView
from rest_framework.authentication import SessionAuthentication, BasicAuthentication
from rest_framework.settings import api_settings

from api.api_utilities import postList, postCreate, str2bool, get_public_posts, getRemotePost
from app.models import Post, Author, Server, RemoteFriend

import datetime

from rest_framework import permissions


# Taken from https://stackoverflow.com/a/37649438
class IsGetOrIsAuthenticated(permissions.BasePermission):

    def has_permission(self, request, view):
        # allow all GET requests
        if request.method == 'GET':
            return True

        # Otherwise, only allow authenticated requests
        # Post Django 1.10, 'is_authenticated' is a read-only attribute
        return request.user and request.user.is_authenticated


class PublicPostView(APIView):
    """
    /api/posts
    """

    permission_classes = (IsAuthenticated,)
    authentication_classes = (SessionAuthentication, BasicAuthentication)

    pagination_class = api_settings.DEFAULT_PAGINATION_CLASS

    def get(self, request):
        remote_id = request.META.get('HTTP_X_AUTHOR_ID')
        response = dict()
        response['query'] = 'posts'
        try:
            remote = Server.objects.get(user=request.user)
            public = Post.objects.all().filter(visibility="PUBLIC").order_by('-published')

            if remote.no_posts:
                response['posts'] = []
                response['success'] = True
                response['message'] = 'Server admin restricted posts.'
                return Response(response, status=403)

            if remote.no_images:
                public = public.exclude(contentType="image/png;base64").exclude(contentType='image/jpeg;base64')

            posts = postList(public)

            if remote.hostname.endswith("/"):
                url = "{}author/{}".format(remote.hostname, remote_id)
            else:
                url = "{}/author/{}/friends/".format(remote.hostname, remote_id)
            req = requests.get(url, auth=(remote.username, remote.password))
            if req.status_code == 200:
                r = req.json()
                friends = r.get('friends')
                for i in friends:
                    get_id = i.get('id')
                    raw_id = get_id.split('/')[-1]
                    try:
                        auth = Author.objects.get(id=raw_id)
                        friend_posts = Post.objects.all().filter(author=auth).filter(visibility="FRIENDS")
                        if remote.no_images:
                            friend_posts = friend_posts.exclude(contentType="image/png;base64").exclude(
                                contentType='image/jpeg;base64')
                        friend_posts = postList(friend_posts)
                        posts.extend(friend_posts)

                    except:
                        print("No authors matched")
        except:
            print("Not a server user")
            public = Post.objects.all().filter(visibility="PUBLIC").order_by('-published')
            posts = postList(public)
            posts = get_public_posts(posts)
            # server = Server.objects.get(hostname=request.)

        posts = sorted(posts, key=lambda k: k['published'], reverse=True)
        page = self.paginate_queryset(posts)
        if page is not None:
            page = self.get_paginated_response(page)
        dat = page.data
        response['posts'] = dat.get('results')
        response['previous'] = dat.get('previous')
        response['next'] = dat.get('next')
        response['count'] = dat.get('count')
        return Response(response, status=200)

    def post(self, request):
        user = request.user
        response = dict()
        try:
            remote = Server.objects.get(user=user)
            if remote:
                response['query'] = 'addPost'
                response['success'] = False
                response['message'] = 'Not authorized to create posts'
                return Response(response, status=403)
            else:
                response['query'] = 'addPost'
                response['success'] = False
                response['message'] = 'Not authorized to create posts'
                return Response(response, status=403)
        except:
            author = user.user
            r = request.POST
            title = r.get('title')
            description = r.get('description')
            visibility = r.get('visibility')
            content = r.get('content')
            contentType = r.get('contentType')
            unlisted = str2bool(r.get('unlisted'))

            if title and description and visibility and content and contentType and (unlisted in [True, False]):
                post = Post.objects.create(
                    author=author, title=title, description=description, visibility=visibility, content=content,
                    contentType=contentType, unlisted=bool(unlisted)
                )
                if post:
                    response['query'] = 'addPost'
                    response['success'] = True
                    response['message'] = 'Post added'

                    return Response(response, status=200)
                else:
                    response['query'] = 'addPost'
                    response['success'] = False
                    response['message'] = 'Post failed to create'

                    return Response(response, status=500)
            else:
                response['query'] = 'addPost'
                response['success'] = False
                response['message'] = 'Missing fields'

                return Response(response, status=500)

    @property
    def paginator(self):
        """
        The paginator instance associated with the view, or `None`.
        """
        if not hasattr(self, '_paginator'):
            if self.pagination_class is None:
                self._paginator = None
            else:
                self._paginator = self.pagination_class()
        return self._paginator

    def paginate_queryset(self, queryset):
        """
        Return a single page of results, or `None` if pagination is disabled.
        """
        if self.paginator is None:
            return None
        return self.paginator.paginate_queryset(queryset, self.request, view=self)

    def get_paginated_response(self, data):
        """
        Return a paginated style `Response` object for the given output data.
        """
        assert self.paginator is not None
        return self.paginator.get_paginated_response(data)


class AuthorVisiblePostView(APIView):
    """
    /author/posts

    For currently authenticated user
    """

    authentication_classes = (SessionAuthentication, BasicAuthentication)
    permission_classes = (IsAuthenticated,)

    def get(self, request):
        remote_id = request.META.get('HTTP_X_AUTHOR_ID')
        if remote_id:
            post_list = list()
            remote = Server.objects.get(user=request.user)
            if remote:
                posts = Post.objects.all().filter(visibility="PUBLIC").order_by('-published')
                post_list.extend(posts)
                if remote.hostname.endswith("/"):
                    url = "{}author/{}".format(remote.hostname, remote_id)
                else:
                    url = "{}/author/{}/friends/".format(remote.hostname, remote_id)
                req = requests.get(url, auth=(remote.username, remote.password))
                if req.status_code == 200:
                    r = req.json()
                    friends = r.get('friends')
                    for i in friends:
                        get_id = i.get('id')
                        raw_id = get_id.split('/')[-1]
                        try:
                            auth = Author.objects.get(id=raw_id)
                            friend_posts = Post.objects.all().filter(author=auth).filter(
                                visibility="FRIENDS") | Post.objects.all().filter(author=auth).filter(
                                visibility="PUBLIC")
                            if remote.no_images:
                                friend_posts = friend_posts.exclude(contentType="image/png;base64").exclude(
                                    contentType='image/jpeg;base64')

                            post_list.extend(friend_posts)

                        except:
                            print("No authors matched")
                    response = dict()
                    response['query'] = 'posts'
                    response['count'] = len(post_list)
                    response['posts'] = postList(post_list)
                    return Response(response, status=200)
        else:
            user = request.user
            posts = Post.objects.all().filter(author__id__in=request.user.user.friends.all()).filter(
                visibility="FRIENDS") | Post.objects.all().filter(
                author__id__in=request.user.user.friends.all()).filter(
                visibility="SERVERONLY") | Post.objects.all().filter(author=user.user) | Post.objects.all().filter(
                visibility="PUBLIC")
            posts = posts.order_by('-published')
        response = dict()
        response['query'] = 'posts'
        response['count'] = len(posts)
        response['posts'] = postList(posts)
        return Response(response, status=200)


class AuthorPostView(APIView):
    """
    author/<uuid:id>/posts

    All posts made by {AUTHOR_ID} visible to the currently authenticated user
    """

    authentication_classes = (SessionAuthentication, BasicAuthentication)
    permission_classes = (IsAuthenticated,)

    def get(self, request, id):
        author = get_object_or_404(Author, id=id)

app/templates/posts/create_post.html
{% extends 'base.html' %}


{% block page_title %}
    404 Group 10 | Create Post
{% endblock %}

{% block content %}
    <h1 class="h3 mb-4 text-gray-800">Create Post</h1>
    <div>
        <form action="" method="POST">
            {% csrf_token %}
            <div class="col-lg-8">
                <!-- /.panel-heading -->
                <div class="form-group row">
                    <label for="id_title" class="col-form-label">Title<span class="text-danger">*</span></label>
                    {{ form.post.errors }}
                    <input type="text" id="id_title" name="title" class="form-control"
                           placeholder="Post title"
                           value="{{ form.title.value|default:"" }}" autofocus required>

                </div>
                <div class="form-group row">
                    <label for="id_description" class="col-form-label">Brief Description<span
                            class="text-danger">*</span></label>

                    <input type="text" id="id_description" name="description" class="form-control"
                           placeholder="Brief description"
                           value="{{ form.description.value|default:"" }}" autofocus required>

                </div>
                <div class="form-group row">
                    <label for="id_text" class="col-form-label">Content<span class="text-danger">*</span></label>

                    <textarea id="id_text" name="content" placeholder="Post Content"
                              class="form-control" required>{{ form.content.value|default:"" }}</textarea>

                </div>
                <div class="form-group row">
                    <label class="col-form-label">Content Type<span class="text-danger">*</span></label>

                    {{ form.contentType }}
                </div>
                <div class="form-group row">
                    <label class="col-form-label">Visibility<span class="text-danger">*</span></label>

                    {{ form.visibility }}
                </div>
                <div class="form-group row">
                    <label class="col-form-label">Visible to<span class="text-danger">*</span></label>

                    {{ form.visibleTo }}
                </div>
                <div class="form-group row">
                    <label class="col-form-label">Unlisted<span class="text-danger">*</span></label>

                    {{ form.unlisted }}
                </div>
            </div>
            {% if messages %}
                <ul class="messages">
                    {% for message in messages %}
                        <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
                    {% endfor %}
                </ul>
            {% endif %}
            <button class="btn btn-primary" type="submit">Submit</button>
        </form>
    </div>
{% endblock %}

app/templates/posts/edit_post.html
{% extends 'base.html' %}


{% block page_title %}
    404 Group 10 | Edit Post
{% endblock %}

{% block content %}
    <h1 class="h3 mb-4 text-gray-800">Create Post</h1>
    <div>
        <form action="" method="POST">
            {% csrf_token %}
            <div class="col-lg-8">
                <!-- /.panel-heading -->
                <div class="form-group row">
                    <label for="id_title" class="col-form-label">Title<span class="text-danger">*</span></label>
                    {{ form.post.errors }}
                    <input type="text" id="id_title" name="title" class="form-control"
                           placeholder="Post title"
                           value="{{ form.title.value|default:"" }}" autofocus required>

                </div>
                <div class="form-group row">
                    <label for="id_description" class="col-form-label">Brief Description<span
                            class="text-danger">*</span></label>

                    <input type="text" id="id_description" name="description" class="form-control"
                           placeholder="Brief description"
                           value="{{ form.description.value|default:"" }}" autofocus required>

                </div>
                <div class="form-group row">
                    <label for="id_text" class="col-form-label">Content<span class="text-danger">*</span></label>

                    <textarea id="id_text" name="content" placeholder="Post Content"
                              class="form-control" required>{{ form.content.value|default:"" }}</textarea>

                </div>
                <div class="form-group row">
                    <label class="col-form-label">Content Type<span class="text-danger">*</span></label>

                    {{ form.contentType }}
                </div>
                <div class="form-group row">
                    <label class="col-form-label">Visibility<span class="text-danger">*</span></label>

                    {{ form.visibility }}
                </div>
                <div class="form-group row">
                    <label class="col-form-label">Visible to<span class="text-danger">*</span></label>

                    {{ form.visibleTo }}
                </div>
                <div class="form-group row">
                    <label class="col-form-label">Unlisted<span class="text-danger">*</span></label>

                    {{ form.unlisted }}
                </div>
            </div>
            {% if messages %}
                <ul class="messages">
                    {% for message in messages %}
                        <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
                    {% endfor %}
                </ul>
            {% endif %}
            <button class="btn btn-primary" type="submit">Submit</button>
        </form>
    </div>
{% endblock %}

app/templates/posts/post_delete.html
{% extends 'base.html' %}


{% block page_title %}
    404 Group 10 | Delete
{% endblock %}

{% block content %}

    <form method="POST" action="">
        {% csrf_token %}
        Are you sure you want to delete this post?
        <input class="btn btn-primary" type="submit" value="Yes"/>
        <a href='{% url 'app:my_posts' %}'>Cancel</a>
    </form>

{% endblock %}

app/templates/posts/post_detail.html
{% extends 'base.html' %}
{% load tz %}


{% block page_title %}
    404 Group 10 | Post Detail
{% endblock %}

{% block content %}
    <h1 class="h3 mb-4 text-gray-800">{{ post.title }}</h1>
    <div class="card shadow mb-4">
        <!-- Card Header - Accordion -->
        <div class="d-block card-header py-3">
            <div class="inline-group">
                {% if post.author.image %}
                    <img class="img-circle" style="border-radius: 50%; object-fit: cover;" width="50" height="50"
                         src="{{ post.author.image.url }}">
                {% else %}
                    <img class="img-circle" style="border-radius: 50%; object-fit: cover;" width="50"
                         height="50"
                         src="https://www.betwext.com/wp-content/uploads/2018/09/blank-profile-picture-973460_640.png"/>
                {% endif %}

                {% if post.remote %}
                    <a href="{% url "app:author_remote" %}?host={{ post.author.url }}"
                       class="ml-2 font-weight-bold text-primary">
                        {{ post.author.username }} | {{ post.author.host_url }}
                    </a>
                {% else %}
                    <a href="/author/{{ post.author.id }}" class="ml-2 font-weight-bold text-primary">
                        {{ post.author.username }}
                    </a>

                {% endif %}
            </div>
        </div>
        <!-- Card Content - Collapse -->
        <div class="collapse show" id="collapseCardExample{{ post.id }}">
            <div class="card-body">
                <h5 class="mb-0 text-gray-800">{{ post.title }}</h5>
                <p class="mb-0 small text-gray">{{ post.description }}</p>
                <p class="small text-gray">{{ post.published|timezone:"America/Edmonton" }}</p>
                <hr>
                <p class="m-4">{{ post.get_content }}</p>
            </div>
        </div>
    </div>

    {% if comments %}
        <h2>Comments</h2>

        {% for comment in comments %}
            {{ comment.author.username }} on {{ comment.published|timezone:"America/Edmonton" }}<br>

            {{ comment.get_comment }}
            <hr>
        {% endfor %}
    {% endif %}

    <div>
        <form action="" method="POST">
            {% csrf_token %}
            <div class="col-lg-8">
                <!-- /.panel-heading -->
                <div class="form-group row">
                    <label for="id_title" class="col-form-label">Comment<span class="text-danger">*</span></label>
                    {{ form.comment.errors }}
                    <textarea id="id_comment" name="comment" class="form-control"
                              placeholder="Enter Comment here" autofocus
                              required>{{ form.comment.value|default:"" }}</textarea>

                </div>
                <div class="form-group row">
                    <label class="col-form-label">Content Type<span class="text-danger">*</span></label>

                    {{ form.contentType }}
                </div>
            </div>
            {% if messages %}
                <ul class="messages">
                    {% for message in messages %}
                        <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
                    {% endfor %}
                </ul>
            {% endif %}
            <button class="btn btn-primary" type="submit">Submit</button>
        </form>
    </div>
{% endblock %}

app/templates/posts/remote_post_detail.html
{% extends 'base.html' %}
{% load tz %}


{% block page_title %}
    404 Group 10 | Post Detail
{% endblock %}

{% block content %}
    <h1 class="h3 mb-4 text-gray-800">{{ post.title }}</h1>
    <div class="card shadow mb-4">
        <!-- Card Header - Accordion -->
        <div class="d-block card-header py-3">
            <div class="inline-group">
                {% if post.author.image %}
                    <img class="img-circle" style="border-radius: 50%; object-fit: cover;" width="50" height="50"
                         src="{{ post.author.image.url }}">
                {% else %}
                    <img class="img-circle" style="border-radius: 50%; object-fit: cover;" width="50"
                         height="50"
                         src="https://www.betwext.com/wp-content/uploads/2018/09/blank-profile-picture-973460_640.png"/>
                {% endif %}

                {% if post.remote %}
                    <a href="{% url "app:author_remote" %}?host={{ post.author.url }}"
                       class="ml-2 font-weight-bold text-primary">
                        {{ post.author.username }} | {{ post.author.host_url }}
                    </a>
                {% else %}
                    <a href="/author/{{ post.author.id }}" class="ml-2 font-weight-bold text-primary">
                        {{ post.author.username }}
                    </a>

                {% endif %}
            </div>
        </div>
        <!-- Card Content - Collapse -->
        <div class="collapse show" id="collapseCardExample{{ post.id }}">
            <div class="card-body">
                <h5 class="mb-0 text-gray-800">{{ post.title }}</h5>
                <p class="mb-0 small text-gray">{{ post.description }}</p>
                <p class="small text-gray">{{ post.published|timezone:"America/Edmonton" }}</p>
                <hr>
                <p class="m-4">{{ post.get_content }}</p>
            </div>
        </div>
    </div>

    {% if comments %}
        <h2>Comments</h2>

        {% for comment in comments %}
            {{ comment.author.username }} on {{ comment.published|timezone:"America/Edmonton" }}<br>

            {{ comment.get_comment }}
            <hr>
        {% endfor %}
    {% endif %}

    <div>
        <form action="" method="POST">
            {% csrf_token %}
            <div class="col-lg-8">
                <!-- /.panel-heading -->
                <div class="form-group row">
                    <label for="id_title" class="col-form-label">Comment<span class="text-danger">*</span></label>
                    {{ form.comment.errors }}
                    <textarea id="id_comment" name="comment" class="form-control"
                              placeholder="Enter Comment here" autofocus
                              required>{{ form.comment.value|default:"" }}</textarea>

                </div>
                <div class="form-group row">
                    <label class="col-form-label">Content Type<span class="text-danger">*</span></label>
                    {{ form.contentType }}
                </div>
            </div>
            {% if messages %}
                <ul class="messages">
                    {% for message in messages %}
                        <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
                    {% endfor %}
                </ul>
            {% endif %}
            <button class="btn btn-primary" type="submit">Submit</button>
        </form>
    </div>
{% endblock %}