SocialDistribution/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('app.urls')),
    path('api/', include('api.urls')),
]

api/urls.py
from django.contrib.auth.decorators import login_required
from django.urls import path, include
from rest_framework import routers

import api.views as views
import api.views.author_views
import api.views.comment_views
import api.views.friend_views
import api.views.post_views

app_name = 'api'

from rest_framework_swagger.views import get_swagger_view

# Taken from https://django-rest-swagger.readthedocs.io/en/latest/
schema_view = get_swagger_view(title='Group 10 Social Distribution Remote API')

urlpatterns = [
    path('', schema_view),
    # Author
    path('author/<uuid:id>', api.views.author_views.AuthorView.as_view(), name='author'),
    path('author/', api.views.author_views.AuthorListView.as_view(), name='author_list'),

    # Posts
    path('posts', api.views.post_views.PublicPostView.as_view(), name='public'),
    path('author/posts', api.views.post_views.AuthorVisiblePostView.as_view(), name='author_visible'),
    path('author-mutual/posts', api.views.post_views.AuthorMutualPostView.as_view(), name='author_mutual_visible'),
    path('author/<uuid:id>/posts', api.views.post_views.AuthorPostView.as_view(), name='author_posts'),
    path('posts/<uuid:id>', api.views.post_views.SinglePostView.as_view(), name='single_post'),

    # Comments
    path('posts/<uuid:id>/comments', api.views.comment_views.CommentsView.as_view(), name='comments'),

    # Friends
    #path('author/<uuid:id>/friends', api.views.friend_views.FriendView.as_view(), name='friends'),
    path('author/<uuid:id>/friends/', api.views.friend_views.FriendResponseView.as_view(), name='friends'),
    path('author/<uuid:id>/friends/<uuid:id2>', api.views.friend_views.IsFriendView.as_view(), name='is_friend'),
    path('author/friends', api.views.friend_views.FriendView2.as_view(), name='friends2'),
    path('author/<uuid:id>/following', api.views.friend_views.FollowingView.as_view(), name='following'),
    path('author/following', api.views.friend_views.FollowingView2.as_view(), name='following2'),
    path('author/<uuid:id>/followers', api.views.friend_views.FollowerView.as_view(), name='followers'),
    path('author/followers', api.views.friend_views.FollowerView2.as_view(), name='followers2'),

    # Friendrequest
    path('friendrequest', api.views.friend_views.FriendRequestView.as_view(), name='friendrequest'),

]

app/urls.py
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static

import app.views.post_views
import app.views.user_views
from app.views import views, post_views, user_views

app_name = 'app'

urlpatterns = [
    path('api_test', views.api_test, name='api_test'),
    # path('api/', include(router.urls)),
    path('', views.index),
    path('index', views.index, name="index"),
    path('accounts/login/', views.login_view, name='login'),
    path('accounts/logout', views.logout_view, name="logout"),
    path('register', views.register_view, name="register"),
    path('create-image', app.views.post_views.create_image_view, name="create_image"),
    path('images/<str:filename>', views.get_image, name="images"),
    path('images/<str:filename>/<str:encoding>', views.get_image, name="images"),
    path('my-posts', app.views.post_views.my_posts_view, name="my_posts"),
    path('create-post', app.views.post_views.create_post_view, name='create_post'),
    path('delete/<uuid:id>/', app.views.post_views.delete_post, name="delete"),
    path('author/<uuid:id>', views.profile_view, name="profile"),
    path('profile', views.my_profile_view, name="my_profile"),
    path('profile/edit/', views.edit_profile, name="edit_profile"),
    path('post/edit/<uuid:id>/', post_views.edit_post, name="edit_post"),
    path('authors', user_views.all_author_view, name="all_authors"),
    path('authors/follow/<uuid:id>/', user_views.follow_view, name="follow"),
    # path('followers/follow/<uuid:id>/', user_views.follow_view, name="followers_follow"),
    path('authors/unfollow/<uuid:id>/', user_views.unfollow_view, name="unfollow"),
    path('authors/unfollow-mutual/<uuid:id>/', user_views.unfollow_mutual_view, name="unfollow_mutual"),
    path('public-posts', app.views.post_views.public_post_view, name="public_posts"),
    path('private-posts', app.views.post_views.private_friends_posts_view, name="private_posts"),
    path('search/', views.search_view, name="search_author"),
    path('new_followers/', user_views.new_followers_view, name="new_followers"),
    path('followers/', user_views.all_followers_view, name="followers"),

    path('mutual-friends/', user_views.mutual_friends_view, name="mutual_friends"),
    path('post-detail/<uuid:id>/', post_views.create_comment_view, name="post_detail"),
    path('foaf-posts', post_views.foaf_posts_view, name="foaf_posts"),
    path('mutual-friend-posts', post_views.mutual_friends_posts_view, name="mutual_friend_posts"),
    path('post/<uuid:id>/', post_views.unlisted_post_view, name="unlisted_post"),

    path('author/remote/', app.views.user_views.profile_remote_view, name="author_remote"),
    path('post-detail/remote/<str:post>', post_views.remote_post_view, name="remote_post"),

    path('friend-request/send/<uuid:id>',user_views.send_friend_request, name='add_friend'),
    path('friend-request/cancel/<uuid:id>',user_views.cancel_friend_request, name='cancel_friend'),
    path('friend-request/accept/<uuid:id>',user_views.accept_friend_request, name='accept_friend'),
    path('friendrequest', user_views.all_requests_view, name="requests"),

    path('remote-friend-request/accept/',user_views.accept_remote_friend_request, name='accept_remote_friend'),
    path('remote-friend-request/cancel/',user_views.cancel_remote_friend_request, name='cancel_remote_friend'),
    path('remote-friend-request/send/<str:uuid>',user_views.send_remote_friend_request, name='add_remote_friend'),
    path('unfollow-remote-mutual/<str:uuid>', user_views.unfriend_remote_mutual_view, name="unfriend_remote_mutual"),

    #path('friendrequest', api_views.friendrequest, name="friendrequest"),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

app/models.py
import uuid

from django.db import models
from django.contrib.auth.models import User
from django.db.models.signals import post_save
from django.dispatch import receiver

from settings_server import *
from django.forms import ModelForm
from django.utils.html import mark_safe
from markdown import markdown


def image_content_to_html(content):
    return mark_safe("<img src=\"" + content + "\" />")


class Author(models.Model):
    """
    user: a local user using the Django User
    username: username from either a local user or remote
    host_url: host url
    github_url: optional github url from an author
    """
    user = models.OneToOneField(User, related_name='user', on_delete=models.CASCADE, blank=True, null=True)
    username = models.CharField(max_length=50, unique=True, blank=True, null=True)
    bio = models.TextField(blank=True, null=True)
    host_url = models.URLField(blank=True, null=True)  # Url of different hosts
    github_url = models.CharField(max_length=100, blank=True, null=True)  # Optional
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False, blank=False)
    url = models.CharField(max_length=150, blank=True, null=True)
    friends = models.ManyToManyField("self", blank=True, related_name='author_friends')
    image = models.ImageField(upload_to='profile_pics', blank=True)

    @property
    def full_name(self):
        if self.user:
            return self.user.get_full_name()

    def __str__(self):
        return "{} - {}".format(str(self.username), self.host_url)

    def save(self, *args, **kwargs):
        if not self.id:
            self.id = uuid.uuid4()
        self.url = "{}/author/{}".format(self.host_url, self.id)
        super(self.__class__, self).save(*args, **kwargs)


class FollowRequest(models.Model):
    author = models.ForeignKey(Author, related_name='author_request', on_delete=models.CASCADE)
    friend = models.ForeignKey(Author, related_name='friend_request', on_delete=models.CASCADE)
    acknowledged = models.BooleanField(default=False)
    date_created = models.DateTimeField(auto_now=True)

    def __str__(self):
        return "{} {} - {}".format(self.author.username, self.friend.username, self.acknowledged)

    def get_following(self):
        return self.friend.username


class FriendRequest(models.Model):
    author = models.ForeignKey(Author, related_name='to_user', on_delete=models.CASCADE)
    friend = models.ForeignKey(Author, related_name='from_user', on_delete=models.CASCADE)
    # acknowledged = models.BooleanField(default=False)
    timestamp = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return "From {}, to {}".format(self.author.username, self.friend.username)


POST_PRIVACY = (
    ('PRIVATE', 'Private'),
    ('SERVERONLY', 'All friends on my host'),
    ('FRIENDS', 'All friends'),
    ('FOAF', 'My friends friends'),
    ('PUBLIC', 'Public'),
)

POST_CONTENT_TYPE = (
    ('text/plain', 'Plain Text'),
    ('text/markdown', 'Markdown'),
    ('image/png;base64', 'PNG Base64'),
    ('image/jpeg;base64', 'JPEG Base64')
)


class Post(models.Model):
    # TODO: Finish this class
    author = models.ForeignKey(Author, related_name='authorPost', on_delete=models.CASCADE)
    published = models.DateTimeField(auto_now=True)
    title = models.CharField(max_length=100, blank=True, null=True)
    description = models.CharField(max_length=50, blank=True, null=True)  # brief description
    visibility = models.CharField(max_length=100, choices=POST_PRIVACY, default='Private')
    visibleTo = models.ManyToManyField(Author, blank=True, related_name='visibleTo')
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False, blank=False)
    content = models.TextField(default="")
    contentType = models.CharField(max_length=100, choices=POST_CONTENT_TYPE, default='Plain Text')
    unlisted = models.BooleanField(default=False)

    def __str__(self):
        return "{} - {} - {}".format(self.author, self.published, self.visibility)

    def __repr__(self):
        return "{} - {} - {}".format(self.author, self.published, self.visibility)

    def get_content(self):
        if self.contentType == "text/markdown":
            return mark_safe(markdown(self.content, safe_mode='escape'))
        elif self.contentType.startswith("image/"):
            return image_content_to_html(self.content)
        else:
            return self.content


class Comment(models.Model):
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False, blank=False)
    post = models.ForeignKey(Post, related_name='CommentPost', on_delete=models.CASCADE)
    author = models.ForeignKey(Author, related_name='authorComment', on_delete=models.CASCADE)
    comment = models.TextField(default="")
    contentType = models.CharField(max_length=100, choices=POST_CONTENT_TYPE, default='Plain Text')
    published = models.DateTimeField(auto_now=True)

    def __str__(self):
        return "{} - {} - {}".format(self.author, self.published, self.id)

    def __repr__(self):
        return "{} - {} - {} ".format(self.author, self.published, self.id)

    def get_comment(self):
        if self.contentType == "text/markdown":
            return mark_safe(markdown(self.comment, safe_mode='escape'))
        else:
            return self.comment


class Server(models.Model):
    # TODO: Finish this class
    hostname = models.CharField(max_length=50, unique=True, blank=True, null=True)
    user = models.OneToOneField(User, related_name='server_user', on_delete=models.CASCADE, blank=True, null=True)
    username = models.CharField(max_length=50, unique=True, blank=True, null=True)
    password = models.CharField(max_length=50, unique=True, blank=True, null=True)
    no_posts = models.BooleanField(default=False)
    no_images = models.BooleanField(default=False)

    def __str__(self):
        return "Hostname: {}".format(self.hostname)


class RemoteComment(models.Model):
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False, blank=False)
    post = models.ForeignKey(Post, related_name='RemoteCommentPost', on_delete=models.CASCADE)
    server = models.ForeignKey(Server, related_name="RemoteServer", on_delete=models.CASCADE)
    author = models.URLField(blank=True, null=True)
    comment = models.TextField(default="")
    contentType = models.CharField(max_length=100, choices=POST_CONTENT_TYPE, default='Plain Text')
    published = models.DateTimeField()

    def __str__(self):
        return "{} - {}".format(self.post.title, self.published)

    def __repr__(self):
        return "{} - {}".format(self.post.title, self.published)

    def get_comment(self):
        if self.contentType == "text/markdown":
            return mark_safe(markdown(self.comment, safe_mode='escape'))
        else:
            return self.comment


@receiver(post_save, sender=User)
def create_user_author(sender, instance, created, **kwargs):
    if created:
        Author.objects.create(user=instance, host_url=DOMAIN)
        instance.user.author_id = uuid.uuid4()
        instance.user.url = "{}/api/author/{}".format(instance.user.host_url, instance.user.author_id)
        instance.user.username = instance.username
        instance.user.save()


class RemoteFriendRequest(models.Model):
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False, blank=False)
    author = models.URLField(blank=True, null=True)  # id
    host = models.URLField(blank=True, null=True)  # host
    displayName = models.CharField(max_length=50, unique=True, blank=True, null=True)  # display name
    url = models.URLField(blank=True, null=True)
    friend = models.ForeignKey(Author, related_name='RemoteFriend', on_delete=models.CASCADE)  # Always a local author
    timestamp = models.DateTimeField(auto_now_add=True)
    server = models.ForeignKey(Server, related_name="RemoteFriendServer", on_delete=models.CASCADE)

    def __str__(self):
        return "From {}, to {}".format(self.author, self.friend.username)


class RemoteFriend(models.Model):
    author = models.ForeignKey(Author, related_name="author_re", on_delete=models.CASCADE, null=True)
    host = models.URLField(blank=True, null=True)  # host
    displayName = models.CharField(max_length=50, unique=True, blank=True, null=True)  # display name
    url = models.URLField(blank=True, null=True)
    friend = models.URLField(blank=True, null=True)
    server = models.ForeignKey(Server, related_name='remote_server', on_delete=models.CASCADE, null=True)


class PendingRemoteFriend(models.Model):
    author = models.ForeignKey(Author, related_name="sender", on_delete=models.CASCADE, null=True)
    host = models.URLField(blank=True, null=True)  # host
    displayName = models.CharField(max_length=50, unique=True, blank=True, null=True)  # display name
    url = models.URLField(blank=True, null=True)
    friend = models.URLField(blank=True, null=True)
    server = models.ForeignKey(Server, related_name='pending_remote_server', on_delete=models.CASCADE, null=True)

app/forms/registration_forms.py
from django import forms
from django.contrib.auth import authenticate
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User


class UserCreateForm(UserCreationForm):
    first_name = forms.CharField(max_length=30, )
    last_name = forms.CharField(max_length=30, )

    class Meta:
        model = User
        fields = ('username', 'first_name', 'last_name', 'password1', 'password2',)


class LoginForm(forms.Form):
    """
    Form used to log in to the web application.
    """
    username = forms.CharField(widget=forms.TextInput(attrs=dict(required=True, max_length=30)), label="Username")
    password = forms.CharField(widget=forms.PasswordInput(attrs=dict(required=True, max_length=30, render_value=False)),
                               label="Password")

    class Meta:
        fields = ['username', 'password']

    def clean(self):
        try:
            User.objects.get(username__iexact=self.cleaned_data['username'])
            user = authenticate(username=self.cleaned_data['username'], password=self.cleaned_data['password'])
            if user is not None:
                if not user.is_authenticated:
                    raise forms.ValidationError("Username/password not found.")
            else:
                raise forms.ValidationError("Username/password not found.")
        except User.DoesNotExist:
            raise forms.ValidationError("Username/password not found")
        return self.cleaned_data

app/templates/edit_profile.html
{% extends 'base.html' %}


{% block page_title %}
    404 Group | My Profile
{% endblock %}

{% block content %}
    <h1 class="h3 mb-4 text-gray-800">Edit My Profile</h1>
    <form action="" method="POST">
        {% csrf_token %}
        <div class="m-2 row">
            <label for="id_first_name" class="col-form-label">First Name
                <span
                        class="text-danger">*</span></label>
            <div class="col-5">
                <input type="text" id="id_first_name" name="first_name"
                       class="form-control" placeholder="First Name"
                       value="{{ user_form.first_name.value|default:"" }}"
                       required>
            </div>
        </div>
        <div class="m-2 row">
            <label for="id_last_name" class="col-form-label">Last Name
                <span
                        class="text-danger">*</span></label>
            <div class="col-5">
                <input type="text" id="id_last_name" name="last_name"
                       class="form-control" placeholder="Last Name"
                       value="{{ user_form.last_name.value|default:"" }}"
                       required>
            </div>
        </div>
        <div class="m-2 row">
            <label for="id_username" class="col-form-label">Username
                <span
                        class="text-danger">*</span></label>
            <div class="col-5">
                <input type="text" id="id_username" name="username"
                       class="form-control" placeholder="Username"
                       value="{{ bio_form.username.value|default:"" }}"
                       required>
            </div>
        </div>

        <div class="m-2 row">
            <label for="id_bio" class="mr-4 col-form-label">Bio
                <span
                        class="text-danger"></span></label>
            <div class="pl-5 col-5">
                <textarea id="id_bio" name="bio"
                          class="form-control "
                          placeholder="Enter short bio here">{{ bio_form.bio.value|default:"" }}</textarea>
            </div>
        </div>
        <div class="m-2 row">
            <label for="id_username" class="col-form-label">Github URL
            </label>
            <div class="col-5">
                <input type="url" id="id_github_url" name="github_url"
                       class="form-control" placeholder="Github url"
                       value="{{ bio_form.github_url.value|default:"" }}"
                >
            </div>
        </div>
        {% if messages %}
            <ul class="messages">
                {% for message in messages %}
                    <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
                {% endfor %}
            </ul>
        {% endif %}
        <button type="submit" class="mt-3 btn btn-primary">Save Changes</button>
    </form>
{% endblock %}

app/templates/footer.html
{% load static %}

<!-- Footer -->
<footer class="sticky-footer bg-white">
    <div class="container my-auto">
        <div class="copyright text-center my-auto">
            <span>Copyright &copy; CMPUT 404 Group 10 2019</span>
        </div>
    </div>
</footer>
<!-- End of Footer -->

app/templates/profile.html
{% extends 'base.html' %}


{% block page_title %}
    404 Group | Profile
{% endblock %}

{% block content %}

    <div class="card-body" style="background-color: white">
        {% if author.image %}
            <img class="m-2" style="object-fit: cover;" width="100" height="100" src="{{ author.image.url }}">
        {% else %}
            <img class="m-2" style="object-fit: cover;" width="100" height="100"
                 src="https://www.betwext.com/wp-content/uploads/2018/09/blank-profile-picture-973460_640.png"/>
        {% endif %}

        {% if author.remote %}
            <h1 class="mb-2 h2 text-gray-800">{{ author.first_name }} {{ author.last_name }}</h1>
        {% else %}
            <h1 class="mb-2 h2 text-gray-800">{{ author.user.first_name }} {{ author.user.last_name }}</h1>
        {% endif %}
        <div class="m-0 h5">
            {{ author.username }}
            {% if author.github_url is not None %}
                <p style="display:inline;">| {{ author.github_url }}</p>
            {% endif %}

        </div>
        <p class="m-0"> {{ author.host_url }}</p>

        <hr>
        {% if author.bio is not None %}
            <p>{{ author.bio }}</p>
        {% endif %}

        {% if author.remote %}
            {% if friends %}
                <a href="{% url 'app:unfriend_remote_mutual' uuid=author.uuid %}?host={{ author.host_url }}"
                   class="btn btn-danger">Unfriend</a>
                {#            {% elif author in pending %}#}
                {#                <a href="" class="btn btn-warning">Pending</a>#}
            {% else %}
                <a href="{% url 'app:add_remote_friend' uuid=author.uuid %}?host={{ author.host_url }}"
                   class="btn btn-success">Add Friend</a>
            {% endif %}
        {% else %}
            {% if author in friends %}
                <a href="{% url 'app:unfollow_mutual' id=author.id %}" class="btn btn-danger">Unfriend</a>
            {% elif author in pending %}
                <a href="" class="btn btn-warning">Pending</a>
            {% elif author != self %}
                <a href="{% url 'app:add_friend' id=author.id %}" class="btn btn-primary">Add Friend</a>
            {% endif %}
        {% endif %}

    </div>
    {#    <a href="/profile/edit" class="btn btn-primary">Edit</a>#}
{% endblock %}

app/templates/sidebar.html
{% load static %}

<!-- Sidebar -->
<ul class="navbar-nav bg-gradient-primary sidebar sidebar-dark accordion" id="accordionSidebar">

    <!-- Sidebar - Brand -->
    <a class="sidebar-brand d-flex align-items-center justify-content-center" href="{% url 'app:index' %}">
        <div class="sidebar-brand-text mx-3">Team 10 Social Distribution</div>
    </a>

    <!-- Divider -->
    <hr class="sidebar-divider">

    <!-- Heading -->
    <div class="sidebar-heading">
        Stream
    </div>

    <!-- Nav Item - Dashboard -->
    <li class="nav-item active">
        <a class="nav-link" href="{% url 'app:index' %}">
            <i class="fas fa-fw fa-tachometer-alt"></i>
            <span>My Stream</span></a>
    </li>


    <li class="nav-item">
        <a class="nav-link" href="{% url 'app:my_posts' %}">
            <i class="fas fa-fw fa-newspaper"></i>
            <span>My Posts</span></a>
    </li>
    <li class="nav-item">
        <a class="nav-link" href="{% url 'app:mutual_friend_posts' %}">
            <i class="fas fa-fw fa-newspaper"></i>
            <span>Mutual Friend Posts</span></a>
    </li>

    <li class="nav-item">
        <a class="nav-link" href="{% url 'app:foaf_posts' %}">
            <i class="fas fa-fw fa-newspaper"></i>
            <span>Friend of Friend Posts</span></a>
    </li>

    <li class="nav-item">
        <a class="nav-link" href="{% url 'app:private_posts' %}">
            <i class="fas fa-fw fa-newspaper"></i>
            <span>Private Posts</span></a>
    </li>

    <li class="nav-item">
        <a class="nav-link" href="{% url 'app:public_posts' %}">
            <i class="fas fa-fw fa-newspaper"></i>
            <span>Public Posts</span></a>
    </li>

    <!-- Divider -->
    <hr class="sidebar-divider">

    <!-- Heading -->
    <div class="sidebar-heading">
        Friends
    </div>

    <li class="nav-item">
        <a class="nav-link" href="{% url 'app:requests' %}">
            <i class="fas fa-fw fa-users"></i>
            <span>Friend Requests</span></a>
    </li>
{#    <li class="nav-item">#}
{#        <a class="nav-link" href="{% url 'app:followers' %}">#}
{#            <i class="fas fa-fw fa-users"></i>#}
{#            <span>Followers</span></a>#}
{#    </li>#}
    <li class="nav-item">
        <a class="nav-link" href="{% url 'app:mutual_friends' %}">
            <i class="fas fa-fw fa-users"></i>
            <span>Mutual Friends</span></a>
    </li>

    <!-- Divider -->
    <hr class="sidebar-divider d-none d-md-block">

    <!-- Sidebar Toggler (Sidebar) -->
    <div class="text-center d-none d-md-inline">
        <button class="rounded-circle border-0" id="sidebarToggle"></button>
    </div>

</ul>

app/templates/topbar.html
{% load static %}

<!-- Topbar -->
    <nav class="navbar navbar-expand navbar-light bg-white topbar mb-4 static-top shadow">

        <!-- Sidebar Toggle (Topbar) -->
        <button id="sidebarToggleTop" class="btn btn-link d-md-none rounded-circle mr-3">
            <i class="fa fa-bars"></i>
        </button>

        <!-- Topbar Search -->
        <form method='GET' action='/search/'
              class="d-none d-sm-inline-block form-inline mr-auto ml-md-3 my-2 my-md-0 mw-100 navbar-search">
            <div class="input-group">
                <input type="text" class="form-control bg-light border-0 small" placeholder="Search for..."
                       aria-label="Search" aria-describedby="basic-addon2" name="q">
                <div class="input-group-append">
                    <button class="btn btn-primary" type="submit">
                        <i class="fas fa-search fa-sm"></i>
                    </button>
                </div>
            </div>
        </form>


        <a href="{% url 'app:create_post' %}" class="mr-3 btn btn-dark">Create New Post</a>
        <a href="{% url 'app:create_image' %}" class="mr-3 btn btn-dark">Upload New Image</a>
        <a href="{% url 'app:all_authors' %}" class="btn btn-facebook">All Authors</a>

{#    <a style="margin-left:20px;" href="{% url 'app:friendrequest' %}" class="btn btn-primary">Friend Request</a>#}



        <!-- Topbar Navbar -->
        <ul class="navbar-nav ml-auto">


            <!-- Nav Item - Search Dropdown (Visible Only XS) -->
            <li class="nav-item dropdown no-arrow d-sm-none">
                <a class="nav-link dropdown-toggle" href="#" id="searchDropdown" role="button" data-toggle="dropdown"
                   aria-haspopup="true" aria-expanded="false">
                    <i class="fas fa-search fa-fw"></i>
                </a>
                <!-- Dropdown - Messages -->
                <div class="dropdown-menu dropdown-menu-right p-3 shadow animated--grow-in"
                     aria-labelledby="searchDropdown">
                    <form class="form-inline mr-auto w-100 navbar-search">
                        <div class="input-group">
                            <input type="text" class="form-control bg-light border-0 small" placeholder="Search for..."
                                   aria-label="Search" aria-describedby="basic-addon2">
                            <div class="input-group-append">
                                <button class="btn btn-primary" type="button">
                                    <i class="fas fa-search fa-sm"></i>
                                </button>
                            </div>
                        </div>
                    </form>
                </div>
            </li>

            <!-- Nav Item - Alerts -->
            <li class="nav-item dropdown no-arrow mx-1">
                <a class="nav-link dropdown-toggle" href="#" id="alertsDropdown" role="button" data-toggle="dropdown"
                   aria-haspopup="true" aria-expanded="false">
                    <i class="fas fa-bell fa-fw"></i>
                    <!-- Counter - Alerts -->
                    <!--TODO: Add if else for alerts here -->
                    {% if request_len > 0 %}
                    <span class="badge badge-danger badge-counter">
                        {{ request_len }}
                    </span>
                    {% endif %}
                </a>
                <!-- Dropdown - Alerts -->
                <div class="dropdown-list dropdown-menu dropdown-menu-right shadow animated--grow-in"
                     aria-labelledby="alertsDropdown">
                    <h6 class="dropdown-header">
                        New Friend Requests
                    </h6>
                    {% for req in requests %}
                    <div class="dropdown-item d-flex align-items-center" href="#">
                        <div class="mr-3">
                            <div class="icon-circle bg-gradient-warning">
                                <i class="fas fa-bell text-white"></i>
                            </div>
                        </div>
                        <div>
                            <div class="small text-gray-500"></div>
                            <span class="font-weight-bold">{{ req.author.username }} - {{ req.date_created }}</span>
                        </div>
                    </div>
                    {% endfor %}
                    <a class="dropdown-item text-center small text-gray-500" href="{% url 'app:new_followers' %}">
                        View All
                        Friend/Follow Requests
                    </a>
                </div>
            </li>

            <div class="topbar-divider d-none d-sm-block"></div>

            <!-- Nav Item - User Information -->
            <li class="nav-item dropdown no-arrow">
                <a class="nav-link dropdown-toggle" href="#" id="userDropdown" role="button" data-toggle="dropdown"
                   aria-haspopup="true" aria-expanded="false">
                    <span class="mr-2 d-none d-lg-inline text-gray-600 small">{{ user.first_name }}</span>
                    <i class="fas fa-laugh-wink"></i>
                    {#                <img class="img-profile rounded-circle" src="{{ req.author.image.url }}">#}
                </a>
                <!-- Dropdown - User Information -->
                <div class="dropdown-menu dropdown-menu-right shadow animated--grow-in" aria-labelledby="userDropdown">
                    <a class="dropdown-item" href="{% url 'app:my_profile' %}">
                        <i class="fas fa-user fa-sm fa-fw mr-2 text-gray-400"></i>
                        Profile
                    </a>
                    <a class="dropdown-item" href="{% url 'app:edit_profile' %}">
                        <i class="fas fa-cogs fa-sm fa-fw mr-2 text-gray-400"></i>
                        Settings
                    </a>
                    <div class="dropdown-divider"></div>
                    <a class="dropdown-item" href="#" data-toggle="modal" data-target="#logoutModal">
                        <i class="fas fa-sign-out-alt fa-sm fa-fw mr-2 text-gray-400"></i>
                        Logout
                    </a>
                </div>
            </li>

        </ul>

    </nav>
<!-- End of Topbar -->